name: kerchunk-cookbook
channels:
  - conda-forge
dependencies:
  - cfgrib
  - dask
  - dask-labextension
  - distributed
  - fastparquet
  - fsspec
  - git
  - h5netcdf
  - h5py
  - ipywidgets
  - jupyter_server<2
  - jupyter-book
  - jupyterlab
  - jupyterlab=3
  - mamba
  - matplotlib
  - netcdf4
  - numcodecs
  - numpy
  - pandas
  - pangeo-forge-recipes==0.10.0
  - pip
  - pooch
  - pyOpenSSL
  - python=3.10
  - rioxarray
  - s3fs
  - scipy
  - tifffile
  - tqdm
  - ujson
  - xarray
  - xarray-datatree
  - zarr
  - hvplot
  - datashader

  - pip:
      - sphinx-pythia-theme
      - "apache-beam[interactive, dataframe]"
      - git+https://github.com/fsspec/kerchunk.git
      - git+https://github.com/carbonplan/xrefcoord.git
