name: dask-binder-template
channels:
  - conda-forge
dependencies:
  - cfgrib
  - dask
  - h5py
  - h5netcdf
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - fsspec
  - matplotlib
  - netcdf4
  - numcodecs
  - numpy
  - s3fs>=2021.08.0
  - scipy
  - tqdm
  - ujson
  - xarray
  - zarr
    # JupyterLab extensions
  - jupyterlab>=3
  - dask-labextension
  - ipywidgets
  - pip:
      - sphinx-pythia-theme
      - git+https://github.com/fsspec/kerchunk.git
